### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by pirrate** [archagon/tasty-imitation-keyboard#55]
While debugging in Xcode i noticed that every time when i change keyboard to my custom keyboard the memory keeps increasing. It starts with 25MB which is fine as Apple mentions in their App Extension Programming Guide https://developer.apple.com/library/ios/documentation/General/Conceptual/ExtensibilityPG/ExtensionCreation.html that memory limits for app extensions are significantly lower than limits imposed on foreground apps. Later when i keep changing keyboards every time it keeps increasing so i reached 60MB with just couple of keyboard changes. I think that is the main reason why keyboard crashes sometimes or does not disappear at all. 
![screen shot 2014-11-30 at 11 09 47 am](https://cloud.githubusercontent.com/assets/9286693/5237076/f64abd08-7881-11e4-991d-080db36bb4f8.png)

**Comment by archagon** [comment]
"Just on iPad when you typing very fast using more than one fingers keyboard lagging a little bit."

Do you get this on the default keyboard? On my iPad 3, which is pretty slow these days, I see it in the default keyboard as well.

**Comment by alariccole** [comment]
Just a note, when in debug mode the memory watchdog may not happen, which is why you wouldn't get an out of memory crash when debugging. There may be a setting for this, not sure. But it sort of makes sense as debugging itself takes some memory.

**Comment by archagon** [comment]
Thanks, that's good to know. In any case, I think I've fixed the biggest memory leaks, though there still seems to be some minor increase when switching keyboards quickly, possibly capped at a certain point.

**Comment by pirrate** [comment]
Memory problem still exists if BannerView is ON. it keeps increasing memory when you change keyboards. When BannerView is off, no reasonable memory problem exists.

**Comment by archagon** [comment]
Ah, thanks for the heads up! Will fix shortly...

**Comment by pirrate** [comment]
Shortly is 1 week i guess? :))

**Comment by archagon** [comment]
"Will" "fix" "shortly"

**Comment by pirrate** [comment]
"still" "hope" "and" "wait" :)

**Comment by pirrate** [comment]
will really appreciate if you will fix that. Because there is still really serious memory leak if BannerView is On.

**Comment by alariccole** [comment]
I'm curious what the cause could be. I see it to. Even a separate keyboard that I built myself exhibits this same issue...I'm thinking it might be constraints, but I'm not sure yet. If I can get instrument to symbolicate, I'll hunt it down.

**Comment by alariccole** [comment]
Still couldn't get Instruments to work for me to know the exact cause, but I do have a workaround. I'm guessing it's outlets etc. that are not being released, then recreated by the system. Could be an iOS bug, could be a misunderstanding of how nibs work. What reduced it for me, significantly, was to *set outlets and other variables manually to nil on viewWillDisappear* (viewDidDisappear didn't get called for the extension in my experience). 

If that doesn't work for you, here's what you could do--raise an exception on viewWillDisappear, crashing the app silently, thus gaining back memory. This loses any caching and will make it slower to load, but keeping the memory footprint low will keep it from crashing while in use, and probably speed up its interaction overall.

Hope this helps!

**Comment by archagon** [comment]
That's a great point. I unfortunately don't have the time to investigate right now, but I'm sure I forgot to do something to release the `IBOutlet`s. A cursory SO search shows that they have to be set to `nil` at some point. So that's probably the correct solution.

Not sure why it would be happening with the banner, though, since my implementation does not use a nib for that.

**Comment by pirrate** [comment]
viewWillDisappear is called in my case. i put self.bannerView = nil, self.forwardingView = nil there but next time when i switch to keyboard it gives BAD_ACCESS error in different places.

**Comment by pirrate** [comment]
Memory leak more observable in spotlight keyboard when bannerview is on. Also, keyboard delays for for half second while switching from symbol keyboard to letter keyboard when you click space button on specialkey (symbol) layout. would really appreciate if you will find couple hours to investigate memory leak problem. This is very cool keyboard but currently it is problem to add more functions into it because of this problems.

**Comment by pirrate** [comment]
Just a reminder for you if you may be forgot to read this tread. Please improve a bit more. This is very useful work.

**Comment by alariccole** [comment]
@pirrate now you're being annoying. Have respect for this person and what they've offered up to you, for free. No one is beholden to you. If it's so important, figure it out yourself.

**Comment by pirrate** [comment]
@alariccole i don`t really want to annoy someone.  i just want to make it even better. From the beginning i was testing and reporting, helping for improvements here. @archagon as an author knows better his code and logic. He can easily/faster improve things here than someone else. I know we all are busy with real works daily and he is too. It is possible that we forgot to read something. This was just a kind reminder for this case. I have respect to him and to all open source community so no need to judge me man. If i do annoy him, he will tell to me and i will excuse and wont to that.

**Comment by archagon** [comment]
Sorry guys, I have a big project I'm working on right now and I need to focus on it pretty much exclusively. I hope to come back and fix all these issues eventually but I can't offer any timelines or guarantees. My main metric for stability is reviews from the keyboards I've put up on the App Store, and nobody's complained about performance or crashes for the past few months, so I think that part is *relatively* good for the time being — at least for newer devices. (I know there are still issues, but they are not nearly as bad as they were a few months ago!)

If you've identified any glaring roadblocks to performance or stability, please submit a pull request and I'll be happy to look into it.

**Comment by nokai** [comment]
Who has found a solution to this problem?

Each time the keyboard is displayed, the memory is being filled and eventually stops working

People will not be used if every X times the keyboard no longer appears

**Comment by zeerakahmed** [comment]
For anyone coming across this thread, I found that @alariccole's suggestion to raise an exception works well in my own keyboard extension. I also found that using autoreleasepools whenever an Objective C framework was being called from Swift helped.
